#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "fire"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
# filemanager = "defx"
    filetree_direction = "left"
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#before'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
autocomplete_method = "coc"
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'float' # also: top/bottom/... and full/float
default_height = 30

[[layers]]
name = "checkers"
lint_engine = "ale"
lint_on_the_fly = true
lint_on_save = true

[[layers]]
name = "ctrlspace"

[[layers]]
name = "debug"

[[layers]]
name = "default"

[[layers]]
name = "edit"

[[layers]]
name = "foldsearch"

[[layers]]
name = "format"
format_on_save = "true" # also lang specific

[[layers]]
name = "fzf"

[[layers]]
name = "git"
git_plugin = "gina"

[[layers]]
name = "gtags"

[[layers]]
name = "incsearch"

[[layers]]
name = "lang#asciidoc"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#dart"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#elm"

[[layers]]
name = "lang#extra"

[[layers]]
name = "gtacs"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#haskell"

[[layers]]
name = "lang#html"
emmet_leader_key = "<C-e>"
emmet_filetypes = ['html']

[[layers]]
name = "lang#ipynb"

[[layers]]
name = "lang#java"
# java_formatter_jar = "" # dl from https://github.com/google/google-java-format

[[layers]]
name = "lang#javascript"
auto_fix = true
enable_flow_syntax = true

[[layers]]
name = "lang#julia"

[[layers]]
name = "lang#kotlin"

[[layers]]
name = "lang#lua"
# repl_command = "executable.lua"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#perl"

[[layers]]
name = "lang#python"
enable_typeinfo = true
format_on_save = true
python_file_head = []

[[layers]]
name = "lang#php"
# php_interpreter = "php"

[[layers]]
name = "lang#rst"

[[layers]]
name = "lang#ruby"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#sh"
format_on_save = true

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#vue"

[[layers]]
name = "lang#xml"

[[layers]]
name = "lsp"
filetypes = ["rust", "python"]
[layers.override_cmd]
rust = ["rls"]
python = ["pyls"]

[[layers]]
name = "sudo"

[[layers]]
  name = "test"
  # [layers.override_config]
    # java_runner = "gradletest"
    # java_gradletest_executable = "./gradlew test"

[[layers]]
name = "tools"

[[layers]]
name = "tools#mpv"

[[layers]]
name = "VersionControl"

[[custom_plugins]]
  repo = "lilydjwg/colorizer"
  on_cmd = ["ColorHighlight", "ColorToggle"]
  merged = false
